create table biosum_calc (
   statecd integer,
   countycd integer,
   plot integer,
   invyr integer,
   subp integer,
   ecodiv text,
   vol_loc_grp text,
   stdorgcd integer,
   balive float,
   precipitation float,
   tree integer,
   spcd integer,
   sitree integer,
   wdldstem integer,
   diahtcd integer,
   dia float,
   ht integer,
   actualht integer,
   upper_dia float,
   upper_dia_ht float,
   centroid_dia float,
   centroid_dia_ht float,
   centroid_dia_ht_actual float,
   sawht integer,
   htdmp float,
   boleht integer,
   formcl integer,
   cr integer,
   statuscd integer,
   standing_dead_cd integer,
   treeclcd integer,
   roughcull integer,
   cull integer,
   cullbf integer,
   cullcf integer,
   cull_fld integer,
   culldead integer,
   cullform integer,
   cullmstop integer,
   cfsnd integer,
   bfsnd integer,
   decaycd integer,
   totage integer,
   plt_cn text,
   cnd_cn text,
   tre_cn text,
   volcfgrs_calc float,
   volcfnet_calc float,
   volcfsnd_calc float,
   volcsgrs_calc float,
   voltsgrs_calc float,
   drybiom_calc float,
   drybiot_calc float,
   drybio_bole_calc float,
   drybio_top_calc float,
   drybio_sapling_calc float,
   drybio_wdld_spp_calc float,
   tree_compilation_status integer,
   tree_compilation_notes text 
);  

create index biosum_calc_plt_cn on biosum_calc (plt_cn);
create index biosum_calc_cnd_cn on biosum_calc (cnd_cn);
create unique index biosum_calc_tre_cn on biosum_calc (tre_cn);

